--1. Write a query to display the custid ,name, age, orderid,orderdate for 
--product books or cd, sort data by name in descending order 
select c.custid,c.custname,c.age,o.orderid,o.orderdate 
from customers c inner join orders o on c.custid = o.custid
where o.product in ('books','cd')
order by c.custname desc

--2. Write a SQL statement to find the list of customers who live in the same city as ajay, and display custid , custname , price (price > 500) 
select c.custid,c.custname,o.price from customers c inner join orders o on c.custid = o.custid
where c.custaddress in (select custaddress from customers where custname = 'Ajay')
and o.price > 500

--3. Write a query to find the name of customers along with order details who purchased   more than two products
SELECT c.custname, COUNT(o.product) AS total_products
FROM customers c
INNER JOIN orders o ON c.custid = o.custid
GROUP BY c.custname
HAVING COUNT(o.product) > 2

--4. A discount of 20% has been announced to all customers who resides in Bangalore . display custid , custname , orderid  and discount price 
SELECT c.custid, c.custname, o.orderid, o.price * 0.80 AS discounted_price
FROM customers c
LEFT JOIN orders o ON c.custid = o.custid
WHERE c.custaddress = 'Bang'


create table products
( 
pid int constraint pk primary key,
pname varchar(20)
)

insert into products values (101,'cd'),(102,'toy')


--5. write a query to join three tables (create products table for the same)
SELECT *FROM customers c
FULL outer JOIN orders o ON c.custid = o.custid
FULL outer JOIN products p ON o.product = p.pname

--6. update price by 5% from orders table for customers who resides in pune and chennai 
UPDATE o SET o.price = o.price * 1.05 FROM orders o inner JOIN customers c ON o.custid = c.custid
WHERE c.custAddress IN ('pune', 'chennai')

--7. create a report in following format Custidord Custname Product Price orderdate cid:100-ordid:1  
--1. Custname should be uppercase 
--2. Display only first 3 character of product 
--3.  The report should be of December 2000
SELECT concat('cid:', c.custid, '-ordid:', o.orderid) as CustidOrder,upper(c.custname) as Custname,
LEFT(o.product, 3) as Product,o.price,o.orderdate from customers c inner join orders o on c.custid = o.custid
where year(o.orderdate)=2000 AND month(o.orderdate)=12


--validations

--8.create table students
create table Students (
    StudentRollNumber int identity(100, 100) primary key,
    StudentName Varchar(50) ,
    DOB date,
    Class int
)

insert into Students values
('Pooja','2001-12-8',8),('preeti','2002-03-01',5)
select*from Students

--I. Student Roll Number should be  autogenerated as (100,200,300…). Alter Command 
--a. DOB cannot be greater then current date 
alter table Students add constraint c_dob check (dob <= getdate())
--b. Class should be between 1 - 10
alter table Students add constraint Class check (class between 1 and 10)

--9.Create Table Stock 
create table Stock (
    StockId varchar(20) primary key,
    MinStockLvl int,
    MaxStockLvl int )

insert into Stock (StockId, MinStockLvl, MaxStockLvl) values
('okj-34-hjk', 27, 45),
('vyu-77-awe', 30, 60),
('mxd-56-qad', 17, 35)

select*from Stock

--The MaxStockLvl should be Greater than MinStockLvl. 
alter table stock add constraint chk_stk1 check (MaxStockLvl > MinStockLvl)

--Stock id should be following format 
--stc-11-aaa 
--Start with 3 alphabets following by – followed by 2 digit followed by – and 
--ending with 3 alphabets 
alter table Stock add constraint chk_stkl 
check (StockId LIKE '[A-Za-z][A-Za-z][A-Za-z]-[0-9][0-9]-[A-Za-z][A-Za-z][A-Za-z]')


--10.Create Table purchase
create table purchase (
    pid int,
    purchasedate date default getdate(),
    serialNo int unique,
    price int,
    Qty int,
    Total as (price * Qty)
)

insert into purchase values(101,'2024-12-06',167,1200,3)
select*from purchase

--Create a rule  qty should be greater than 1
alter table purchase add constraint chk_Qty check (Qty > 1);

--Create a rule where price should be between 1000 and  7000 
alter table purchase add constraint chk_Price check (Price between 1000 and 7000);













